# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: phrosendo
      MYSQL_USER: teste
      MYSQL_PASSWORD: Zmkd@100
      MYSQL_ROOT_PASSWORD: Zmkd@100
    ports:
      - "3306:3306"
    volumes:
      - mysql_db:/var/lib/mysql
volumes:
  mysql_db: 